## 2 sum problem
- Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.
- *Assumption*: Exactly one solution is possible
- *Thought process*:
    - Is the arr sorted (2 pointer works fine)
    - Unsorted (Dictionary works fine)

In [21]:
def two_sum_sorted(arr,target):
    i = 0
    j = len(arr)-1
    while i<j:
        if arr[i]+arr[j] == target:
            return i,j       
        elif arr[i]+arr[j] < target:
            i+=1
        else:
            j-=1
    return -1

output = two_sum_sorted([2,7,11,15],9)

In [22]:
output

(0, 1)

In [23]:
def hash_set_unsorted(arr,target):
    complement_set = set()
    for num in arr:
        complement = target-num
        if complement in complement_set:
            return num,complement
        else:
            complement_set.add(num)
    return -1

output = hash_set_unsorted([2,5,3,4,9],6)
output

(4, 2)

## Longest Consecutive Seq

- Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence.
- You must write an algorithm that runs in O(n) time

In [24]:
import pandas as pd

df = pd.DataFrame(
    [[1,2,3],[4,5,6],[7,8,9]],
    index = [10,11,12],
    columns= ['a','b','c']
)

In [25]:
df

    a  b  c
10  1  2  3
11  4  5  6
12  7  8  9

In [28]:
df1 = pd.melt(df)

In [29]:
df1

  variable  value
0        a      1
1        a      4
2        a      7
3        b      2
4        b      5
5        b      8
6        c      3
7        c      6
8        c      9

In [38]:
df2 = pd.concat([df,df1],axis=1)

In [39]:
df2

      a    b    c variable  value
10  1.0  2.0  3.0      NaN    NaN
11  4.0  5.0  6.0      NaN    NaN
12  7.0  8.0  9.0      NaN    NaN
0   NaN  NaN  NaN        a    1.0
1   NaN  NaN  NaN        a    4.0
2   NaN  NaN  NaN        a    7.0
3   NaN  NaN  NaN        b    2.0
4   NaN  NaN  NaN        b    5.0
5   NaN  NaN  NaN        b    8.0
6   NaN  NaN  NaN        c    3.0
7   NaN  NaN  NaN        c    6.0
8   NaN  NaN  NaN        c    9.0

In [37]:
df1.pivot(columns='variable', values='value')

variable    a    b    c
0         1.0  NaN  NaN
1         4.0  NaN  NaN
2         7.0  NaN  NaN
3         NaN  2.0  NaN
4         NaN  5.0  NaN
5         NaN  8.0  NaN
6         NaN  NaN  3.0
7         NaN  NaN  6.0
8         NaN  NaN  9.0

In [40]:
df = pd.DataFrame(
{"a" : [4 ,5, 6], 
"b" : [7, 8, 9], 
"c" : [10, 11, 12]},    
index = pd.MultiIndex.from_tuples(
[('d', 1), ('d', 2),
('e', 2)], names=['n', 'v']))

In [41]:
df

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [42]:
# importing pandas library from 
# python
import pandas as pd

# Creating an array of names
arrays = ['Sohom','Suresh','kumkum','subrata']

# Creating an array of ages
age= [10, 11, 12, 13]

# Creating an array of marks
marks=[90,92,23,64]

# Using MultiIndex.from_arrays, we are
# combining the arrays together along 
# with their names and creating multi-index 
# with each element from the 3 arrays into
# different rows
multi_index = pd.MultiIndex.from_arrays([arrays,age,marks], names=('names', 'age','marks'))
# Showing the above data
# print(multi_index)

In [43]:
multi_index

MultiIndex([(  'Sohom', 10, 90),
            ( 'Suresh', 11, 92),
            ( 'kumkum', 12, 23),
            ('subrata', 13, 64)],
           names=['names', 'age', 'marks'])

In [44]:
type(multi_index)

pandas.core.indexes.multi.MultiIndex

In [45]:
df7 = pd.DataFrame({'Names':arrays},index=multi_index)

In [46]:
df7

                     Names
names   age marks
Sohom   10  90       Sohom
Suresh  11  92      Suresh
kumkum  12  23      kumkum
subrata 13  64     subrata